### ISSUE TITLE
Include feature area in POI zoom calculation

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#195]
Today we show *all* features from a kind class at the same initial zoom, but this results in a boring and busy, poorly balanced map. 

For instance, we start showing hospitals first, but we end up showing a mix a large & important hospitals and small and less important clinics at the same initial zoom. Instead only the large & important hospitals should be shown at first, and then the smaller, less important clinics should be added progressively in later zooms.

Many POIs are technically labeling landuse AOIs and building featuers and we can leverage the parent's area to throttle the POIs zoom (first adopting the same landuse / building area thresholds and then refining them to be better for POIs – for instance, we see some delta between landuse area, landuse-labels area, and building area for calculating label visibility today.

**Comment by nvkelso** [comment]
I'm seeing some more POIs, earlier (good), but we need more and earlier – at least in San Francisco. Let's try adjusting the area thresholds &/or the zoom offsets in the earlier #222 PR.

**Comment by zerebubuth** [comment]
Here's some stuff I've pulled out. Note that the text is all busy because I've enabled a text label for _every single_ point, so you can see everything that's in the data. I've also disabled all the landuse areas, because I haven't merged the logic for those yet.

![195-sf-z12](https://cloud.githubusercontent.com/assets/271360/10080159/e60b55b6-62e5-11e5-90f2-16a72b164db4.png)

![195-sf-z13](https://cloud.githubusercontent.com/assets/271360/10080162/ea03c14e-62e5-11e5-9da5-0a690b2fc71b.png)

![195-sf-z14](https://cloud.githubusercontent.com/assets/271360/10080165/ec5c046a-62e5-11e5-9abf-1bf8ec1a81fc.png)

**Comment by zerebubuth** [comment]
@nvkelso, it would be really helpful if you could give me some feedback on the images above and whether stuff is coming in too early, too late, or the wrong stuff is visible, etc... Just bear in mind that it doesn't include any of the landuse area centroids - I'm working on that and hopefully will have some screenshots of that soon.

**Comment by nvkelso** [comment]
Generally this is a huge improvement, thank you! 

Should we roll this out incrementally? (What you have already seems good enough to move to prod if you think the code is good enough.)

I've marked up the images. Here's the summary, images down farther.

**Please make these types of features visible earlier**, as annotated on the images:

1. Big churches
2. Museums
3. Convention centers
4. Rail stations (earlier than subway stations)
5. Subway stations (they are often underground)
6. Large shopping centers
7. Large marina
8. City halls
9. Important towers
10. Large named buildings (that's should be tracked separately, examples Cow Palace and Ferry Building)
11. Sometimes there are duplicate icons for a university (there should only be one until the feature is much larger / better zoom).
12. Sometimes other features inside a university/hospital AOI get shown as an icon at low zooms (only one should be shown until later).

We should probably show screenshots of New York and London, too.

![untitled 2](https://cloud.githubusercontent.com/assets/853051/10095226/ee961a5e-631c-11e5-9b11-f753bc0cc8c1.png)

![untitled 3](https://cloud.githubusercontent.com/assets/853051/10095229/f4a4bdba-631c-11e5-85a1-1617c272bc11.png)

![untitled 4](https://cloud.githubusercontent.com/assets/853051/10095232/f8b9f3ca-631c-11e5-9e0f-11f957a8fc9e.png)

**Comment by zerebubuth** [comment]
Latest screenshots, based on the work in #265.

# San Francisco

## Zoom 11

![195-z11](https://cloud.githubusercontent.com/assets/271360/10172774/05bbe88e-66d9-11e5-8466-ddf9e712c2b8.png)

## Zoom 12

There's a high density of POIs around Golden Gate Park, which I think would be best addressed by #266 rather than further tweaking.

![195-z12](https://cloud.githubusercontent.com/assets/271360/10172781/094a31d6-66d9-11e5-9bac-de626aa559ff.png)

## Zoom 13

There's still some duped labels in here, which it would be good to get rid of in #267.

![195-z13](https://cloud.githubusercontent.com/assets/271360/10172784/0b234088-66d9-11e5-81f0-b6ac22a60e4f.png)

## Zoom 14

![195-z14](https://cloud.githubusercontent.com/assets/271360/10172788/0d6de5fa-66d9-11e5-9015-ee31a9324f01.png)

# New York City

## Zoom 11

![195-nyc-z11](https://cloud.githubusercontent.com/assets/271360/10172789/0f69dd64-66d9-11e5-9a6f-ef6632356168.png)

## Zoom 12

![195-nyc-z12](https://cloud.githubusercontent.com/assets/271360/10172790/124c1600-66d9-11e5-8721-21a8da009b28.png)

## Zoom 13

Most of the subway stations kick in all together at this zoom - possibly they're all point features. It would be nice to differentiate on "importance", perhaps by pulling the number of different lines it's part of out of the relation?

![195-nyc-z13](https://cloud.githubusercontent.com/assets/271360/10172791/14fae228-66d9-11e5-8639-fa1320ab155f.png)

## Zoom 14

![195-nyc-z14](https://cloud.githubusercontent.com/assets/271360/10172792/18478044-66d9-11e5-8f85-a0ebda3eb596.png)

**Comment by zerebubuth** [comment]
@nvkelso what do you think? OK to go, and we'll come back to fix #266, #267 and any additional tweaks in another round?

**Comment by nvkelso** [comment]
Generally looking fantastic! You've added a lot of clarity to the map :)

Regarding z13 in NYC and all the subway stations, let's track that using #268 as a separate problem. Are you suggesting we should lower the default layer to zoom 14 instead of 13 (you propose 13, it is a blanket 12 now) for those, though?

I'm still not seeing big churches? (they aren't visible now, so not a regression.) Is that because there isn't any landuse polygon with those tags? Should we open a separate issue to adopt this logic for POIs vis-a-vis building polygons?

It looks like you're using the area to calculate the visible airports, can you show what that looks like at zooms 9 and 10? We've usually had too many of those show up, I want to make sure we're seeing less after this change. Alternatively we could load this into dev and have a look around.

**Comment by zerebubuth** [comment]
> It looks like you're using the area to calculate the visible airports, can you show what that looks like at zooms 9 and 10? We've usually had too many of those show up, I want to make sure we're seeing less after this change.

# San Francisco

## Zoom 9

No airports... we had too many, now do we have too few? Do we want them at zoom 9? It should be easy to pull them up a zoom, if that's what you want.

![195-sf-z9](https://cloud.githubusercontent.com/assets/271360/10191632/969e3e44-676d-11e5-9da6-a78da527e5e7.png)

## Zoom 10

Here we've got two: SF International (seems appropriate) but also Oakland, which is actually a larger airport in terms of area. If we need to distinguish between Oakland and SFO, then we probably need to bring in another dataset such as passenger numbers.

![195-sf-z10](https://cloud.githubusercontent.com/assets/271360/10191642/aa34cb26-676d-11e5-9c21-fec80c0a0515.png)

# New York City

## Zoom 9

Again, no airports. Although note that this extract is much smaller than the Bay Area one, so might be missing a few that didn't make the cut.

![195-nyc-z9](https://cloud.githubusercontent.com/assets/271360/10191683/1abb401e-676e-11e5-94cb-296216e5e5ae.png)

## Zoom 10

This zoom has Newark and JFK, which seems appropriate.

![195-nyc-z10](https://cloud.githubusercontent.com/assets/271360/10191682/172b2bbc-676e-11e5-9c91-7d813e95a806.png)

**Comment by zerebubuth** [comment]
Here's a list of the top 20 airports on my local machine and the zoom they currently cut in at. Let me know if these can be dropped by a zoom or half or something.

```
 min_zoom |                      name                       
----------+-------------------------------------------------
        8 | Andrews AFB
        9 | John F. Kennedy International Airport
        9 | Sacramento International Airport
        9 | McClellan Airfield
        9 | Metropolitan Oakland International Airport
        9 | Newark Liberty International Airport
        9 | San Francisco International Airport
        9 | Gnoss Field Airport
       10 | Norman Y. Mineta San Jose International Airport
       10 | Fayetteville Regional Airport
       10 | 
       10 | Charles M. Schulz - Sonoma County Airport
       10 | Moffett Federal Airfield
       10 | LaGuardia Airport
       10 | Teterboro Airport
       10 | Westchester County Airport
       10 | Stockton Metropolitan Airport
       10 | airport
       10 | Farmingdale Airport
       10 | Eagle County Regional Airport
```

**Comment by zerebubuth** [comment]
After 918ba48 in #265 to pull places of worship up a few zooms:

# San Francisco

## Zoom 12

![195-churches-sf-z12](https://cloud.githubusercontent.com/assets/271360/10194698/14697172-6782-11e5-9b0c-8b0627fc8faa.png)

## Zoom 13

![195-churches-sf-z13](https://cloud.githubusercontent.com/assets/271360/10194768/6b2c9a5c-6782-11e5-894f-608ae6cda599.png)

## Zoom 14

![195-churches-sf-z14](https://cloud.githubusercontent.com/assets/271360/10194816/a091728a-6782-11e5-8f95-5f4898982f8b.png)

# New York City

## Zoom 12

![195-churches-nyc-z12](https://cloud.githubusercontent.com/assets/271360/10194854/d40409fc-6782-11e5-83bc-d8c7dbf6798a.png)

## Zoom 13

![195-churches-nyc-z13](https://cloud.githubusercontent.com/assets/271360/10194863/da567b50-6782-11e5-8ad6-457cf0e1a19a.png)

## Zoom 14

![195-churches-nyc-z14](https://cloud.githubusercontent.com/assets/271360/10194873/e0b464a8-6782-11e5-90f1-c3c065597eda.png)

**Comment by nvkelso** [comment]
* **Churches**: Too many churches now, but right progression (revealing more on each zoom). Please adjust the formula so what's visible at zoom 12 is instead visible at zoom 13, what's visible now at 13 moves to z14.

**Comment by nvkelso** [comment]
* **Airports**: We're good to go. The table looks good, the maps look good. 

I suspect the stylesheet has an area filter that needs adjusting at zooms 9/10 so more tile data renders, I'll investigate that.

**Comment by nvkelso** [comment]
* **Universities**: Let's go with what you have now. Generally we should move the visibility one zoom later, I've added detail to a new issue: https://github.com/mapzen/vector-datasource/issues/269.

**Comment by zerebubuth** [comment]
Churches fixed in #265, so when that's merged this is done.

**Comment by nvkelso** [comment]
This is so awesome :)

**Comment by nvkelso** [comment]
I've updated the landuse area filters in the scene file. #213 covers porting some of that logic server side... when you disable those filters now a crazy number of `label_position` features show on the map, but that's always been the case and is already covered by that earlier issue. This is ready for prod.
