### ISSUE TITLE
Roads on edge of landuse AOIs broken up

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#289]
**NYC example:**

Merrick Ave North and Salisbury Park Dr are getting chunked up.

https://www.openstreetmap.org/edit?#map=16/40.7429/-73.5787

<img width="913" alt="screen shot 2015-10-03 at 15 14 12" src="https://cloud.githubusercontent.com/assets/853051/10265425/8b2f090c-69e4-11e5-96e3-2c4138b72d2b.png">

**SF Bay Area example:**

The boundary roads along Redwood Regional Park and Chabot Regional Park (Redwood Dr, etc) are getting chunked up. Looking at the data, looks like the road and the park boundary aren't topologically the same, but I think that might be true in ground truth (because of parcel boundaries & etc) – in any case we should allow for this.

<img width="1129" alt="screen shot 2015-10-03 at 15 17 26" src="https://cloud.githubusercontent.com/assets/853051/10265424/8b2d765a-69e4-11e5-80fd-fc3196b293ec.png">

<img width="638" alt="screen shot 2015-10-03 at 15 18 31" src="https://cloud.githubusercontent.com/assets/853051/10265423/8b136530-69e4-11e5-8e59-4d5181c371e2.png">

**Another SF example** that's less obvious north of SF near Fairfield:
#12/38.2628/-122.1076

<img width="468" alt="screen shot 2015-10-03 at 15 34 32" src="https://cloud.githubusercontent.com/assets/853051/10265421/6d042d40-69e4-11e5-91a8-6d9c2a5ce63c.png">

**Comment by nvkelso** [comment]
I expect the parts of the road inside the landuse AOI to get `landuse_kind`, but the part outside of the AOI should still be returned (without `landuse_kind` added). That the part outside is missing should be investigated.

**Comment by zerebubuth** [comment]
Looks like this has been fixed as part of  mapzen/TileStache#72 (in commit https://github.com/mapzen/TileStache/commit/d61f3477acc27e68ee0ac3b197c16f1460181469). It needs wider verification in dev, but I was able to produce the screenshots below from my own system running master which do now show this problem any more.

It seems that the issue was that the intersection was producing a GeometryCollection containing both lines and points and we were previously checking if the actual geometry type was equal to the original and, since `points|lines != lines`, it was dropping them. This was changed in that commit to filter the geometry type of interest from any set returned in a GeometryCollection, which seems to have addressed the issue.

## Area near Salisbury Park Dr.

### Zoom 15

![salisbury-park-dr-z15](https://cloud.githubusercontent.com/assets/271360/10576180/355d58a4-7659-11e5-8231-c1aac5f0fa9b.jpg)

### Zoom 16

![salisbury-park-dr-z16](https://cloud.githubusercontent.com/assets/271360/10576187/3cc20d6a-7659-11e5-9118-5a11065e222f.jpg)

## Chabot Regional Park, zoom 14

The "dashed effect" appearance of this road doesn't look nice, in my opinion, and bloats the size of the tile as each "dash" is a separate feature. However, fixing that [is a separate issue](https://github.com/mapzen/vector-datasource/issues/314).

![chabot-regional-park-z14](https://cloud.githubusercontent.com/assets/271360/10576193/4ac87764-7659-11e5-9191-51fc9b141ac7.jpg)

## Suisun City, zoom 12

![suisun-city-z12](https://cloud.githubusercontent.com/assets/271360/10576196/53c8c120-7659-11e5-8eb7-2edf19cc18d0.jpg)

**Comment by nvkelso** [comment]
So this is configuration changed (in https://github.com/mapzen/vector-datasource/issues/201), no further engineering work needed? Looks like #201 still needs to be taken to `dev`. I'll keep this on me until I can verify that #201 fixes it.

**Comment by zerebubuth** [comment]
I thought we took #201 to dev already. I just took this screenshot from dev, which seems to show it okay. Could you check that you've cleared the cache and are looking at `url: //vector.dev.mapzen.com/osm/all/{z}/{x}/{y}.topojson`, please? If you're still seeing old tiles then we have a problem...

![chabot_park_z14](https://cloud.githubusercontent.com/assets/271360/10635675/795f7cfe-77f2-11e5-93b6-0aa2a76f449c.jpg)

**Comment by nvkelso** [comment]
Testing more with a cleared cache, I see Chabot Regional Park in `dev` showing the fix (matches the screenshot above), good.

But [zoom 16 around Salisbury Park Dr](https://www.openstreetmap.org/edit?#map=16/40.7429/-73.5787) is still broken. But zoom 15 and zoom 17 are fine. Tested in Chrome and Safari on Mac.

z15:
<img width="356" alt="z15" src="https://cloud.githubusercontent.com/assets/853051/10643024/8d04d6f4-77d5-11e5-8dfa-112feb10cea0.png">

z16:
<img width="651" alt="z16" src="https://cloud.githubusercontent.com/assets/853051/10643025/8d03ea3c-77d5-11e5-8f9e-bce78d150936.png">

z17:
<img width="757" alt="z17" src="https://cloud.githubusercontent.com/assets/853051/10643023/8cec6916-77d5-11e5-8ca4-8685c9e24cdb.png">

Could those zoom 16 tiles be stuck on dev?

**Comment by zerebubuth** [comment]
Yup, I see the same on dev, but it's fixed when looking at my local setup. Seems like that tile hasn't generated yet. We can either wait for it to regenerate, or try to fiddle with the stack to make it generate?

**Comment by rmarianski** [comment]
I was fiddling with dev earlier so it might not have gotten to this tile. I just re-enqueued zoom 16 tiles in dev. Does it look ok now?

**Comment by nvkelso** [comment]
LGTM
